// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCnZTPo5p2dZ2SKCyZWGTr6eVWBLPYiaQ',
    appId: '1:3049101719:web:0cc7141e6f7f356b980cd2',
    messagingSenderId: '3049101719',
    projectId: 'smarthome-efa61',
    authDomain: 'smarthome-efa61.firebaseapp.com',
    databaseURL: 'https://smarthome-efa61-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-efa61.firebasestorage.app',
    measurementId: 'G-EHEBRS534F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiZBKm8HW5nRUmcYBGSQ9Ue03A2DwhE0',
    appId: '1:3049101719:android:d535ff7ade05b4c1980cd2',
    messagingSenderId: '3049101719',
    projectId: 'smarthome-efa61',
    databaseURL: 'https://smarthome-efa61-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-efa61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjhtlowFqULYW0OQeenU1xjJ-uJu7KM0',
    appId: '1:3049101719:ios:c7bfa7ba9ce7c516980cd2',
    messagingSenderId: '3049101719',
    projectId: 'smarthome-efa61',
    databaseURL: 'https://smarthome-efa61-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-efa61.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjhtlowFqULYW0OQeenU1xjJ-uJu7KM0',
    appId: '1:3049101719:ios:c7bfa7ba9ce7c516980cd2',
    messagingSenderId: '3049101719',
    projectId: 'smarthome-efa61',
    databaseURL: 'https://smarthome-efa61-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-efa61.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCnZTPo5p2dZ2SKCyZWGTr6eVWBLPYiaQ',
    appId: '1:3049101719:web:57658ee444c134ab980cd2',
    messagingSenderId: '3049101719',
    projectId: 'smarthome-efa61',
    authDomain: 'smarthome-efa61.firebaseapp.com',
    databaseURL: 'https://smarthome-efa61-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-efa61.firebasestorage.app',
    measurementId: 'G-04Y8Q5L1P0',
  );
}
